# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import elecont_pb2 as elecont__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in elecont_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ElecontStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetState = channel.unary_unary(
                '/elecont.Elecont/GetState',
                request_serializer=elecont__pb2.Empty.SerializeToString,
                response_deserializer=elecont__pb2.State.FromString,
                _registered_method=True)
        self.GetSignalsById = channel.unary_unary(
                '/elecont.Elecont/GetSignalsById',
                request_serializer=elecont__pb2.SignalsId.SerializeToString,
                response_deserializer=elecont__pb2.SignalPool.FromString,
                _registered_method=True)
        self.GetSignalsByGuid = channel.unary_unary(
                '/elecont.Elecont/GetSignalsByGuid',
                request_serializer=elecont__pb2.SignalsGuid.SerializeToString,
                response_deserializer=elecont__pb2.SignalPool.FromString,
                _registered_method=True)
        self.GetSignalsByType = channel.unary_unary(
                '/elecont.Elecont/GetSignalsByType',
                request_serializer=elecont__pb2.ElecontSignalType.SerializeToString,
                response_deserializer=elecont__pb2.SignalPool.FromString,
                _registered_method=True)
        self.GetCommandsById = channel.unary_unary(
                '/elecont.Elecont/GetCommandsById',
                request_serializer=elecont__pb2.SignalsId.SerializeToString,
                response_deserializer=elecont__pb2.CommandPool.FromString,
                _registered_method=True)
        self.GetCommandsByGuid = channel.unary_unary(
                '/elecont.Elecont/GetCommandsByGuid',
                request_serializer=elecont__pb2.SignalsGuid.SerializeToString,
                response_deserializer=elecont__pb2.CommandPool.FromString,
                _registered_method=True)
        self.GetCommandsByType = channel.unary_unary(
                '/elecont.Elecont/GetCommandsByType',
                request_serializer=elecont__pb2.ElecontSignalType.SerializeToString,
                response_deserializer=elecont__pb2.CommandPool.FromString,
                _registered_method=True)
        self.CreateEmptyReport = channel.unary_unary(
                '/elecont.Elecont/CreateEmptyReport',
                request_serializer=elecont__pb2.ReportId.SerializeToString,
                response_deserializer=elecont__pb2.Result.FromString,
                _registered_method=True)
        self.DeleteReport = channel.unary_unary(
                '/elecont.Elecont/DeleteReport',
                request_serializer=elecont__pb2.ReportId.SerializeToString,
                response_deserializer=elecont__pb2.Result.FromString,
                _registered_method=True)
        self.DeleteAllReport = channel.unary_unary(
                '/elecont.Elecont/DeleteAllReport',
                request_serializer=elecont__pb2.Empty.SerializeToString,
                response_deserializer=elecont__pb2.Result.FromString,
                _registered_method=True)
        self.AddSignalToReport = channel.unary_unary(
                '/elecont.Elecont/AddSignalToReport',
                request_serializer=elecont__pb2.Report.SerializeToString,
                response_deserializer=elecont__pb2.Result.FromString,
                _registered_method=True)
        self.GetSignalsByReport = channel.unary_unary(
                '/elecont.Elecont/GetSignalsByReport',
                request_serializer=elecont__pb2.ReportId.SerializeToString,
                response_deserializer=elecont__pb2.SignalPool.FromString,
                _registered_method=True)
        self.GetChangedSignals = channel.unary_unary(
                '/elecont.Elecont/GetChangedSignals',
                request_serializer=elecont__pb2.Empty.SerializeToString,
                response_deserializer=elecont__pb2.SignalPool.FromString,
                _registered_method=True)
        self.GetChangedSignalsByReport = channel.unary_unary(
                '/elecont.Elecont/GetChangedSignalsByReport',
                request_serializer=elecont__pb2.ReportId.SerializeToString,
                response_deserializer=elecont__pb2.SignalPool.FromString,
                _registered_method=True)
        self.GetAllSignals = channel.unary_unary(
                '/elecont.Elecont/GetAllSignals',
                request_serializer=elecont__pb2.Empty.SerializeToString,
                response_deserializer=elecont__pb2.SignalPool.FromString,
                _registered_method=True)
        self.GetAllCommands = channel.unary_unary(
                '/elecont.Elecont/GetAllCommands',
                request_serializer=elecont__pb2.Empty.SerializeToString,
                response_deserializer=elecont__pb2.CommandPool.FromString,
                _registered_method=True)
        self.SetSignals = channel.unary_unary(
                '/elecont.Elecont/SetSignals',
                request_serializer=elecont__pb2.SignalPool.SerializeToString,
                response_deserializer=elecont__pb2.Result.FromString,
                _registered_method=True)
        self.GetSignalsStream = channel.unary_stream(
                '/elecont.Elecont/GetSignalsStream',
                request_serializer=elecont__pb2.Empty.SerializeToString,
                response_deserializer=elecont__pb2.Signals.FromString,
                _registered_method=True)
        self.GetCommandsStream = channel.unary_stream(
                '/elecont.Elecont/GetCommandsStream',
                request_serializer=elecont__pb2.Empty.SerializeToString,
                response_deserializer=elecont__pb2.Commands.FromString,
                _registered_method=True)
        self.GetAllObjectsData = channel.unary_unary(
                '/elecont.Elecont/GetAllObjectsData',
                request_serializer=elecont__pb2.Empty.SerializeToString,
                response_deserializer=elecont__pb2.Objects.FromString,
                _registered_method=True)
        self.GetSignalByGuid = channel.unary_unary(
                '/elecont.Elecont/GetSignalByGuid',
                request_serializer=elecont__pb2.Guid.SerializeToString,
                response_deserializer=elecont__pb2.Signal.FromString,
                _registered_method=True)
        self.GetCommandByGuid = channel.unary_unary(
                '/elecont.Elecont/GetCommandByGuid',
                request_serializer=elecont__pb2.Guid.SerializeToString,
                response_deserializer=elecont__pb2.Command.FromString,
                _registered_method=True)
        self.SetSignal = channel.unary_unary(
                '/elecont.Elecont/SetSignal',
                request_serializer=elecont__pb2.Signal.SerializeToString,
                response_deserializer=elecont__pb2.Result.FromString,
                _registered_method=True)
        self.SetCommand = channel.unary_unary(
                '/elecont.Elecont/SetCommand',
                request_serializer=elecont__pb2.Command.SerializeToString,
                response_deserializer=elecont__pb2.Result.FromString,
                _registered_method=True)


class ElecontServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSignalsById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSignalsByGuid(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSignalsByType(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCommandsById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCommandsByGuid(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCommandsByType(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateEmptyReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAllReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddSignalToReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSignalsByReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChangedSignals(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChangedSignalsByReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllSignals(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllCommands(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSignals(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSignalsStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCommandsStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllObjectsData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSignalByGuid(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCommandByGuid(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSignal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ElecontServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=elecont__pb2.Empty.FromString,
                    response_serializer=elecont__pb2.State.SerializeToString,
            ),
            'GetSignalsById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSignalsById,
                    request_deserializer=elecont__pb2.SignalsId.FromString,
                    response_serializer=elecont__pb2.SignalPool.SerializeToString,
            ),
            'GetSignalsByGuid': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSignalsByGuid,
                    request_deserializer=elecont__pb2.SignalsGuid.FromString,
                    response_serializer=elecont__pb2.SignalPool.SerializeToString,
            ),
            'GetSignalsByType': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSignalsByType,
                    request_deserializer=elecont__pb2.ElecontSignalType.FromString,
                    response_serializer=elecont__pb2.SignalPool.SerializeToString,
            ),
            'GetCommandsById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCommandsById,
                    request_deserializer=elecont__pb2.SignalsId.FromString,
                    response_serializer=elecont__pb2.CommandPool.SerializeToString,
            ),
            'GetCommandsByGuid': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCommandsByGuid,
                    request_deserializer=elecont__pb2.SignalsGuid.FromString,
                    response_serializer=elecont__pb2.CommandPool.SerializeToString,
            ),
            'GetCommandsByType': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCommandsByType,
                    request_deserializer=elecont__pb2.ElecontSignalType.FromString,
                    response_serializer=elecont__pb2.CommandPool.SerializeToString,
            ),
            'CreateEmptyReport': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateEmptyReport,
                    request_deserializer=elecont__pb2.ReportId.FromString,
                    response_serializer=elecont__pb2.Result.SerializeToString,
            ),
            'DeleteReport': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteReport,
                    request_deserializer=elecont__pb2.ReportId.FromString,
                    response_serializer=elecont__pb2.Result.SerializeToString,
            ),
            'DeleteAllReport': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAllReport,
                    request_deserializer=elecont__pb2.Empty.FromString,
                    response_serializer=elecont__pb2.Result.SerializeToString,
            ),
            'AddSignalToReport': grpc.unary_unary_rpc_method_handler(
                    servicer.AddSignalToReport,
                    request_deserializer=elecont__pb2.Report.FromString,
                    response_serializer=elecont__pb2.Result.SerializeToString,
            ),
            'GetSignalsByReport': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSignalsByReport,
                    request_deserializer=elecont__pb2.ReportId.FromString,
                    response_serializer=elecont__pb2.SignalPool.SerializeToString,
            ),
            'GetChangedSignals': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChangedSignals,
                    request_deserializer=elecont__pb2.Empty.FromString,
                    response_serializer=elecont__pb2.SignalPool.SerializeToString,
            ),
            'GetChangedSignalsByReport': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChangedSignalsByReport,
                    request_deserializer=elecont__pb2.ReportId.FromString,
                    response_serializer=elecont__pb2.SignalPool.SerializeToString,
            ),
            'GetAllSignals': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllSignals,
                    request_deserializer=elecont__pb2.Empty.FromString,
                    response_serializer=elecont__pb2.SignalPool.SerializeToString,
            ),
            'GetAllCommands': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllCommands,
                    request_deserializer=elecont__pb2.Empty.FromString,
                    response_serializer=elecont__pb2.CommandPool.SerializeToString,
            ),
            'SetSignals': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSignals,
                    request_deserializer=elecont__pb2.SignalPool.FromString,
                    response_serializer=elecont__pb2.Result.SerializeToString,
            ),
            'GetSignalsStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GetSignalsStream,
                    request_deserializer=elecont__pb2.Empty.FromString,
                    response_serializer=elecont__pb2.Signals.SerializeToString,
            ),
            'GetCommandsStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GetCommandsStream,
                    request_deserializer=elecont__pb2.Empty.FromString,
                    response_serializer=elecont__pb2.Commands.SerializeToString,
            ),
            'GetAllObjectsData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllObjectsData,
                    request_deserializer=elecont__pb2.Empty.FromString,
                    response_serializer=elecont__pb2.Objects.SerializeToString,
            ),
            'GetSignalByGuid': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSignalByGuid,
                    request_deserializer=elecont__pb2.Guid.FromString,
                    response_serializer=elecont__pb2.Signal.SerializeToString,
            ),
            'GetCommandByGuid': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCommandByGuid,
                    request_deserializer=elecont__pb2.Guid.FromString,
                    response_serializer=elecont__pb2.Command.SerializeToString,
            ),
            'SetSignal': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSignal,
                    request_deserializer=elecont__pb2.Signal.FromString,
                    response_serializer=elecont__pb2.Result.SerializeToString,
            ),
            'SetCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.SetCommand,
                    request_deserializer=elecont__pb2.Command.FromString,
                    response_serializer=elecont__pb2.Result.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'elecont.Elecont', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('elecont.Elecont', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Elecont(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/elecont.Elecont/GetState',
            elecont__pb2.Empty.SerializeToString,
            elecont__pb2.State.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSignalsById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/elecont.Elecont/GetSignalsById',
            elecont__pb2.SignalsId.SerializeToString,
            elecont__pb2.SignalPool.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSignalsByGuid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/elecont.Elecont/GetSignalsByGuid',
            elecont__pb2.SignalsGuid.SerializeToString,
            elecont__pb2.SignalPool.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSignalsByType(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/elecont.Elecont/GetSignalsByType',
            elecont__pb2.ElecontSignalType.SerializeToString,
            elecont__pb2.SignalPool.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCommandsById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/elecont.Elecont/GetCommandsById',
            elecont__pb2.SignalsId.SerializeToString,
            elecont__pb2.CommandPool.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCommandsByGuid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/elecont.Elecont/GetCommandsByGuid',
            elecont__pb2.SignalsGuid.SerializeToString,
            elecont__pb2.CommandPool.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCommandsByType(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/elecont.Elecont/GetCommandsByType',
            elecont__pb2.ElecontSignalType.SerializeToString,
            elecont__pb2.CommandPool.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateEmptyReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/elecont.Elecont/CreateEmptyReport',
            elecont__pb2.ReportId.SerializeToString,
            elecont__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/elecont.Elecont/DeleteReport',
            elecont__pb2.ReportId.SerializeToString,
            elecont__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteAllReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/elecont.Elecont/DeleteAllReport',
            elecont__pb2.Empty.SerializeToString,
            elecont__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddSignalToReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/elecont.Elecont/AddSignalToReport',
            elecont__pb2.Report.SerializeToString,
            elecont__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSignalsByReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/elecont.Elecont/GetSignalsByReport',
            elecont__pb2.ReportId.SerializeToString,
            elecont__pb2.SignalPool.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChangedSignals(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/elecont.Elecont/GetChangedSignals',
            elecont__pb2.Empty.SerializeToString,
            elecont__pb2.SignalPool.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChangedSignalsByReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/elecont.Elecont/GetChangedSignalsByReport',
            elecont__pb2.ReportId.SerializeToString,
            elecont__pb2.SignalPool.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllSignals(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/elecont.Elecont/GetAllSignals',
            elecont__pb2.Empty.SerializeToString,
            elecont__pb2.SignalPool.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllCommands(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/elecont.Elecont/GetAllCommands',
            elecont__pb2.Empty.SerializeToString,
            elecont__pb2.CommandPool.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetSignals(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/elecont.Elecont/SetSignals',
            elecont__pb2.SignalPool.SerializeToString,
            elecont__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSignalsStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/elecont.Elecont/GetSignalsStream',
            elecont__pb2.Empty.SerializeToString,
            elecont__pb2.Signals.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCommandsStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/elecont.Elecont/GetCommandsStream',
            elecont__pb2.Empty.SerializeToString,
            elecont__pb2.Commands.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllObjectsData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/elecont.Elecont/GetAllObjectsData',
            elecont__pb2.Empty.SerializeToString,
            elecont__pb2.Objects.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSignalByGuid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/elecont.Elecont/GetSignalByGuid',
            elecont__pb2.Guid.SerializeToString,
            elecont__pb2.Signal.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCommandByGuid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/elecont.Elecont/GetCommandByGuid',
            elecont__pb2.Guid.SerializeToString,
            elecont__pb2.Command.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetSignal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/elecont.Elecont/SetSignal',
            elecont__pb2.Signal.SerializeToString,
            elecont__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/elecont.Elecont/SetCommand',
            elecont__pb2.Command.SerializeToString,
            elecont__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
